version: '3.8'

services:

  redis:
    image: redis:7.0.7-alpine
    container_name: redis_container

  postgres_db:
    image: postgres:13.9
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 3

  django:
    image: django-devops-py:latest
    build: ./server
    container_name: django_app_container
    depends_on:
      postgres_db:
        condition: service_healthy

  celery:
    image: sirna-celery:latest
    build: ./server
    container_name: celery_app_container
    depends_on:
      - postgres_db
      - redis
      - django
