version: '3.8'

services:

  redis:
    restart: always

  postgres_db:
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA : /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    entrypoint: ["bash", "django-test-entrypoint.sh"]
    volumes:
      - ./server:/app
      - django_volume:/django_volume
    env_file:
      - .env
    ports:
      - '8000:8000'
      - '80:80'

  celery:
    command:  celery -A devops_py worker -l DEBUG
    env_file:
      - .env
    volumes:
      - ./server:/app
      - django_volume:/django_volume
    depends_on:
      - postgres_db
      - redis
      - django

volumes:
  django_volume:
  pgdata:
