"""
Django settings for devops_py project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os

from .base_settings import *  # pylint: disable=W0401,W0614

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': '5432',
    }
}

REDIS_HOST = 'redis'

STATIC_URL = 'statics/'
MEDIA_URL = 'media/'

MEDIA_ROOT = '/django_volume/media/'
STATIC_ROOT = '/django_volume/static/'
